In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
from sklearn import svm

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
df = pd.read_csv('/content/drive/MyDrive/diabetes.csv')

In [16]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [17]:
X = df.drop(columns = 'Outcome', axis = 1)
Y = df['Outcome']

In [18]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [19]:
Y.shape

(768,)

In [20]:
scaler = StandardScaler()

In [22]:
scaler.fit(X)

StandardScaler()

In [23]:
standardize_data = scaler.transform(X)

In [24]:
standardize_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [25]:
standardize_data.shape

(768, 8)

In [26]:
X = standardize_data

In [27]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [28]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [30]:
X_train.shape

(614, 8)

In [31]:
X_test.shape

(154, 8)

In [32]:
Y_train.shape

(614,)

In [33]:
Y_test.shape

(154,)

In [34]:
classifier = svm.SVC(kernel = 'linear')

In [35]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [36]:
X_train_prediction = classifier.predict(X_train)

In [38]:
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [39]:
training_data_accuracy

0.7866449511400652

In [40]:
X_test_prediction = classifier.predict(X_test)

In [41]:
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [42]:
test_data_accuracy

0.7727272727272727

Predictive System

In [54]:
input_data = (8,183,64,0,0,23.3,0.672,32)
input_data_as_numpy_array = np.asarray(input_data)

In [44]:
type(input_data_as_numpy_array)

numpy.ndarray

In [45]:
type(input_data)

tuple

In [46]:
input_data_as_numpy_array

array([ 1.   , 89.   , 66.   , 23.   , 94.   , 28.1  ,  0.167, 21.   ])

In [48]:
input_data_as_numpy_array.shape

(8,)

In [55]:
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

In [49]:
input_data_reshaped.shape

(1, 8)

In [56]:
std_data = scaler.transform(input_data_reshaped)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [51]:
std_data

array([[-0.84488505, -0.99820778, -0.16054575,  0.15453319,  0.12330164,
        -0.49404308, -0.92076261, -1.04154944]])

In [57]:
prediction = classifier.predict(std_data)

In [58]:
prediction

array([1])

In [59]:
if prediction[0] == 0:
  print('Person is Non-Diabetic')
else:
  print('Person is Diabetic')

Person is Diabetic
